### PR TITLE
Fix model type of SwinIR configs

### PR DESCRIPTION
**Pull request by rlaphoenix**
SRGANModel is not what is used in either Redux or original traiNNer, it's SwinIRModel.

### CODE REVIEW

**Comment by Kim2091** [comment]
I appreciate the PR, but SRGANModel is used to enable GAN loss with SwinIR. It's an unfortunate side effect of the way it had to be implemented. Refer to this comment: https://discord.com/channels/547949405949657098/549520096612188181/1025879413943963739

**Comment by rlaphoenix** [comment]
I see, however, am I wrong in saying this would then be training an SRGAN model and not a SwinIR model?

For other's reading in the future I thought I'd quote the conversation linked:

> joey: based on the code im looking at, it should already work
> kim: sadly it does not
> joey: SwinIRModel inherits from SRModel which has the changes
and SwinIRModel doesnt override the things that would need to be changed
it could be broken in SrModel i guess
lemme check
> kim: (config file)
this is my config
training log
(log file)
> joey: ok yeah it didnt have color or avg
done
> kim: thank you
it's working
hm
actually GANLoss doesn't seem to be working
`2022-10-01 16:51:09,261 INFO: [SwinI..][epoch: 10, iter:  14,300, lr:(1.000e-04,)] [eta: 15:29:56, time (data): 0.125 (0.000)] l_pix: 4.2417e-02 l_percep: 1.1806e+01 l_contextual: 2.3114e-01 l_color: 2.6216e-02`
color is though
> joey: thats because it inherits srmodel not srganmodel
> kim: ah
> joey: change the model type at the top from SwinIRModel to SRGANModel if you wanna use gan loss
> if that breaks anything else, idk what to tell ya

**Comment by rlaphoenix** [comment]
I also want to state that it does not work for me if I use SRGANModel over SwinIRModel. That was one of the root issues I had that we discussed on Discord.

**Comment by Kim2091** [comment]
> I see, however, am I wrong in saying this would then be training an SRGAN model and not a SwinIR model?

It wouldn't train an SRGAN model. I believe it just uses the losses supported by SRGANModel rather than SwinIRModel. The generator config here controls the model that's being trained:

> network_g:
>   type: SwinIR
>   upscale: 1
>   in_chans: 3
...

Most of my experience with BasicSR and traiNNer-redux by extension is just from training on it. I don't know all of the functions of it. Joey would be far more helpful with this side of things. It is worth noting though that all of my SwinIR model attempts have been trained with SRGANModel at the top of the config rather than SwinIRModel, and it worked fine.

We could set SwinIRModel as the default and add in a comment like:
`# Change to SRGANModel to enable GAN loss support`
Would that be satisfactory?

**Comment by rlaphoenix** [comment]
I've deleted the fork mistaking this as being closed/pulled. However, you are free to keep this closed for the meantime. Perhaps it can be brought up later.

Your comment about making it the default with a comment makes the most sense in my opinion. Just it feels weird to me to set it to SRGAN to use GAN, maybe SwinIR isn't meant to use GAN loss?

You can see Joey seems to state as such as well, that SwinIR inherits from SRModel, not SRGANModel. This would make sense as well. I guess it just means there's no harm funkying it up to support GAN, not like it's gospel not to.

**Pull request closed without merging**
